# Generated by Django 3.1 on 2024-01-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use', models.CharField(blank=True, max_length=50, null=True)),
                ('line', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=255)),
                ('use', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumanName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('use', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Identifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('unknown', 'Unknown')], max_length=10)),
                ('birth_date', models.DateField()),
                ('marital_status', models.CharField(blank=True, max_length=20, null=True)),
                ('multiple_birth', models.BooleanField(default=False)),
                ('address', models.ManyToManyField(to='mypracticeapp.Address')),
                ('identifier', models.ManyToManyField(to='mypracticeapp.Identifier')),
                ('name', models.ManyToManyField(to='mypracticeapp.HumanName')),
                ('telecom', models.ManyToManyField(to='mypracticeapp.ContactPoint')),
            ],
        ),
    ]
