# Generated by Django 3.1 on 2024-01-15 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypracticeapp', '0002_patient_fhir_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactPoint',
            new_name='Contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='identifier',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telecom',
        ),
        migrations.AddField(
            model_name='patient',
            name='addresses',
            field=models.ManyToManyField(blank=True, related_name='patient_addresses', to='mypracticeapp.Contact'),
        ),
        migrations.AddField(
            model_name='patient',
            name='telecoms',
            field=models.ManyToManyField(blank=True, related_name='patient_telecoms', to='mypracticeapp.Contact'),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='name',
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='HumanName',
        ),
        migrations.DeleteModel(
            name='Identifier',
        ),
    ]
