# Generated by Django 3.1 on 2024-01-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypracticeapp', '0003_auto_20240115_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True),
        ),
    ]
